module DfmWeb
  module CssBundle
    SOURCES = %w[
      fonts/redhat pure/pure pure/grids-responsive pure/visibility pure/gutter
      layout flash nav nav_colors style_background style forms tables
      layout_media dark_mode print
    ].freeze

    ROOT = File.expand_path("../..", __dir__)
    DIRECTORY = File.join(ROOT, "app/assets/stylesheets/dfm_web")
    TARGET = File.join(DIRECTORY, "dfm_web.css")

    def self.content
      header = "/* Generated by rake dfm_web:assets:build. Edit the source stylesheets, not this file. */\n"
      stylesheets = SOURCES.map { |name| File.read(File.join(DIRECTORY, "#{name}.css")) }
      debug = ".debug { box-shadow: 0 0 1px red, 0 0 2px black; }\n" \
        ".debug-all, .debug-all * { box-shadow: 0 0 1px white, 0 0 2px black; }\n"
      header + stylesheets.join("\n") + "\n" + debug
    end

    def self.write
      File.write(TARGET, content)
    end

    def self.check!
      raise "CSS bundle is stale; run rake dfm_web:assets:build" unless File.read(TARGET) == content
    end
  end
end